const Data = [
  {
    image:
      "https://www.rocketmortgage.com/resources-cmsassets/RocketMortgage.com/Article_Images/Large_Images/TypesOfHomes/types-of-homes-hero.jpg",
    title: "townhouse 1",
    price: "1800",
    dis: "hello",
    room: "4 bedrooms",
    bathroom: "1 bathroom",
    location: "Noida",
    area: "7x10m2",
    property: "guesthouse",
  },
  {
    image:
      "https://www.brightonhomes-idaho.com/2020/wp-content/uploads/2020/03/Available_Homes-600x400.jpg",
    title: "townhouse 2",
    price: "1200",
    dis: "hello",
    room: "4 bedrooms",
    bathroom: "1 bathroom",
    location: "Goa",
    area: "2x10m2",
    property: "land",
  },
  {
    image:
      "https://media.istockphoto.com/id/1272128530/photo/home-with-blue-siding-and-stone-fa%C3%A7ade-on-base-of-home.jpg?b=1&s=170667a&w=0&k=20&c=vdpWpslhj_oGFrLxbQ1N0nNmGj_gU-2qbfUSpdArziU=",
    title: "townhouse 3",
    price: "1700",
    dis: "hello",
    room: "2 bedrooms",
    bathroom: "1 bathroom",
    location: "Pune",
    area: "5x10m2",
    property: "penthouse",
  },
  {
    image:
      "https://media.hhomesltd.com/images/54286/01HOU-Bridgeland65s-224-M_orig.jpg",
    title: "townhouse 4",
    price: "1100",
    dis: "hello",
    room: "1 bedrooms",
    bathroom: "1 bathroom",
    location: "Agra",
    area: "4x10m2",
    property: "land",
  },
  {
    image:
      "https://www.gannett-cdn.com/presto/2022/04/20/NOKL/4a8e0638-e8d7-42cb-b257-7bc2b008eff7-2501_Summit_Crossing_Parkway_Norman_-_1st_Oklahoma_Homes.JPEG",
    title: "townhouse 5",
    price: "900",
    dis: "hello",
    room: "1 bedrooms",
    bathroom: "1 bathroom",
    location: "Noida",
    area: "7x10m2",
    property: "flat",
  },
  {
    image:
      "https://www.bhg.com/thmb/3Vf9GXp3T-adDlU6tKpTbb-AEyE=/750x0/filters:no_upscale():max_bytes(150000):strip_icc():format(webp)/white-modern-house-curved-patio-archway-c0a4a3b3-aa51b24d14d0464ea15d36e05aa85ac9.jpg",
    title: "townhouse 6",
    price: "12300",
    dis: "hello",
    room: "4 bedrooms",
    bathroom: "2 bathroom",
    location: "Gurugram",
    area: "5x10m2",
    property: "guesthouse",
  },
  {
    image:
      "https://files.simonds.com.au/assets/MainSimondsWebsite/Homepage/SEO%20Panels/owilSINyEQpC5HKhQ21WD2GFvbe2ciroRT4tLFyC.jpg",
    title: "townhouse 7",
    price: "1400",
    dis: "hello",
    room: "2 bedrooms",
    bathroom: "1 bathroom",
    location: "Noida",
    area: "4x10m2",
    property: "house",
  },
  {
    image:
      "https://media.istockphoto.com/id/524085051/photo/beautiful-exterior-of-new-luxury-home-at-twilight.jpg?s=612x612&w=0&k=20&c=wPqEpJkL22wE3NHSCgdWXq2FC8a-KvSCpP7XRIZHuOU=",
    title: "townhouse 8",
    price: "1600",
    dis: "hello",
    room: "2 bedrooms",
    bathroom: "1 bathroom",
    location: "Goa",
    area: "2x10m2",
    property: "flat",
  },
  {
    image:
      "https://masterton.com.au/wp-content/uploads/2019/04/700x460-Accent-MK2-Executive.jpg",
    title: "townhouse 9",
    price: "2000",
    dis: "hello",
    room: "4 bedrooms",
    bathroom: "2 bathroom",
    location: "Agra",
    area: "5x10m2",
    property: "apartment",
  },
  {
    image:
      "https://static01.nyt.com/images/2019/06/25/realestate/25domestic-zeff/a1c1a1a36c9e4ff8adcb958c4276f28d-jumbo.jpg",
    title: "townhouse 10",
    price: "1500",
    dis: "hello",
    room: "4 bedrooms",
    bathroom: "1 bathroom",
    location: "pune",
    area: "2x10m2",
    property: "apartment",
  },
  {
    image:
      "https://cdn.vox-cdn.com/thumbor/FrnLQTpuAoAmp0GZRZctSSdkC04=/0x0:3000x2000/1200x0/filters:focal(0x0:3000x2000):no_upscale()/cdn.vox-cdn.com/uploads/chorus_asset/file/21905363/iStock_185930591.jpg",
    title: "townhouse 11",
    price: "1000",
    dis: "hello",
    room: "1 bedrooms",
    bathroom: "1 bathroom",
    location: "pune",
    area: "3x10m2",
    property: "penthouse",
  },
  {
    image:
      "https://www.bhg.com/thmb/VM0_g9o-R-ZC1XXOYQfpPkfVrkg=/1500x0/filters:no_upscale():max_bytes(150000):strip_icc()/craftsman-style-home-fenced-front-yard-a9b9e28b-32f0e418576742dfb598498f019ff0e7.jpg",
    title: "townhouse 12",
    price: "2200",
    dis: "hello",
    room: "3 bedrooms",
    bathroom: "2 bathroom",
    location: "pune",
    area: "3x10m2",
    property: "house",
  },
];

export default Data;
